name: ci
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    container:
      # Ref: https://github.community/t5/GitHub-Actions/docker-pull-from-public-GitHub-Package-Registry-fail-with-quot/m-p/32782
      image: superstructor/clojure:openjdk-11-lein-2.9.1-node-browsers
    steps:
      - uses: actions/checkout@v1
      - run: lein karma-once
