name: cd
on:
  push:
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+*"

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    container:
      image: docker.pkg.github.com/day8/dockerfile-for-dev-ci-image/dev-ci:0.1
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - run: lein ci 
  release:
    name: Release
    needs: test
    runs-on: ubuntu-18.04
    container:
      image: docker.pkg.github.com/day8/dockerfile-for-dev-ci-image/dev-ci:0.1
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          # All of the Git history is required for day8/lein-git-inject to determine the version string.
          fetch-depth: 0
      - name: Run lein release
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_TOKEN: ${{ secrets.CLOJARS_TOKEN }}
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          lein release
