name: ci
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    container:
      image: docker.pkg.github.com/day8/dockerfile-for-dev-ci-image/dev-ci:0.1
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      - run: lein ci
